name: Build Playwright Layer (AL2023 / Python 3.12)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python (host helper)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create wheelhouse (manylinux_2_28)
        run: |
          mkdir -p wheelhouse
          docker run --rm -v "${{ github.workspace }}/wheelhouse":/wheels -v "${{ github.workspace }}/requirements.txt":/requirements.txt \
            quay.io/pypa/manylinux_2_28_x86_64:latest /bin/bash -lc "\
              /opt/python/cp312-cp312/bin/pip wheel --no-deps --wheel-dir=/wheels -r /requirements.txt && \
              chown -R $(id -u):$(id -g) /wheels"

      - name: Prepare out dir
        run: |
          rm -rf out || true
          mkdir -p out/python/lib/python3.12/site-packages
          mkdir -p out/lib64
          chmod -R a+rwX out || true

      - name: Build layer in Amazon Linux 2023 (system libs + python packages + browsers)
        run: |
          set -euo pipefail
          echo "Starting amazonlinux container to build the layer..."
          docker run --rm --entrypoint /bin/bash \
            -v "${{ github.workspace }}/wheelhouse":/wheels \
            -v "${{ github.workspace }}/out":/out \
            -v "${{ github.workspace }}/requirements.txt":/requirements.txt \
            public.ecr.aws/amazonlinux/amazonlinux:2023 -lc "\
              set -euo pipefail; \
              echo '=== update & install base packages ==='; \
              yum -y update || true; \
              yum -y install -y which findutils python3 python3-devel python3-pip tar xz unzip curl fontconfig freetype freetype-devel glibc-langpack-en || true; \
              echo '=== install common libs for chromium (tolerate missing) ==='; \
              yum -y install -y nspr nss nss-util dbus-glib atk at-spi2-atk expat cairo libX11 libXcomposite libXcursor libXdamage libXrandr libXtst libXrender libXfixes libXext libXScrnSaver libxcb libxshmfence libxkbcommon mesa-libgbm libdrm alsa-lib gtk3 pango || true; \
              echo 'python3 location:'; which python3 || true; python3 --version || true; \
              echo '=== ensure pip exists ==='; \
              python3 -m ensurepip --upgrade || true; \
              if ! python3 -m pip --version >/dev/null 2>&1; then \
                echo 'pip not present, fetching get-pip.py'; \
                curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py || true; \
                python3 /tmp/get-pip.py || true; \
              fi; \
              python3 -m pip install --upgrade pip setuptools wheel || true; \
              echo '=== install python wheels into /out from wheelhouse ==='; \
              python3 -m pip install --no-index --find-links=/wheels --no-deps --target=/out/python/lib/python3.12/site-packages -r /requirements.txt || true; \
              echo '=== install playwright into /out (ensures module available) ==='; \
              python3 -m pip install --no-deps --upgrade playwright --target=/out/python/lib/python3.12/site-packages || true; \
              chmod -R a+rwX /out || true; \
              echo '=== set PYTHONPATH to include /out site-packages and install browsers to /tmp ==='; \
              export PYTHONPATH=/out/python/lib/python3.12/site-packages; \
              export PLAYWRIGHT_BROWSERS_PATH=/tmp/ms-playwright; \
              echo 'PYTHONPATH='${PYTHONPATH}; echo 'PLAYWRIGHT_BROWSERS_PATH='${PLAYWRIGHT_BROWSERS_PATH}; \
              echo '=== run playwright install (this may take a while) ==='; \
              PYTHONPATH=$PYTHONPATH PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_BROWSERS_PATH python3 -m playwright install --with-deps chromium 2>&1 | tee /tmp/playwright-install.log || true; \
              echo '=== copy browsers to /out/.cache/ms-playwright ==='; \
              mkdir -p /out/.cache/ms-playwright; \
              cp -a /tmp/ms-playwright/* /out/.cache/ms-playwright/ 2>/dev/null || true; \
              echo '=== collect native libs into /out/lib64 if present ==='; \
              mkdir -p /out/lib64 || true; \
              for lib in libnspr4.so libnss3.so libnssutil3.so libdbus-1.so libatk-1.0.so libatk-bridge-2.0.so libexpat.so.1 libatspi.so.0 libX11.so.6 libXcomposite.so.1 libXdamage.so.1 libXext.so.6 libXfixes.so.3 libXrandr.so.2 libgbm.so.1 libxcb.so.1 libxkbcommon.so.0 libudev.so.1 libasound.so.2; do \
                for p in /usr/lib64/$lib /usr/lib/$lib /lib64/$lib /lib/$lib; do \
                  if [ -f \"$p\" ]; then cp -v \"$p\" /out/lib64/ || true; fi; \
                done; \
              done; \
              echo '=== permissions & finalizing ==='; \
              chmod -R a+rwX /out || true; \
              if [ -f /tmp/playwright-install.log ]; then cp /tmp/playwright-install.log /out/playwright-install.log || true; fi; \
              find /out -type f -name headless_shell -exec chmod +x {} \\; || true; \
              find /out -type f -name chrome -exec chmod +x {} \\; || true; \
              chown -R 1000:1000 /out || true; \
              echo '=== amazonlinux container step complete ==='"

      - name: Post-process out move browsers if installed inside site-packages
        run: |
          set -e
          if [ -d out/python/lib/python3.12/site-packages/playwright ]; then
            candidates=$(find out/python/lib/python3.12/site-packages/playwright -maxdepth 4 -type d -name "chrome-linux" -print || true)
            if [ -n "$candidates" ]; then
              mkdir -p out/.cache/ms-playwright
              for d in $candidates; do
                src=$(dirname "$(dirname "$d")")
                cp -a "$src"/* out/.cache/ms-playwright/ || true
              done
              chmod -R a+rX out/.cache/ms-playwright || true
            fi
          fi

      - name: Show out size and sample files
        run: |
          du -sh out || true
          echo "TOP-LEVEL OUT:"
          ls -la out || true
          echo "SITE-PACKAGES:"
          ls -la out/python/lib/python3.12/site-packages | head -n 160 || true
          if [ -d out/.cache/ms-playwright ]; then
            echo ".cache content sample:"
            ls -la out/.cache/ms-playwright | head -n 40 || true
          fi
          if [ -d out/lib64 ]; then
            echo "lib64 sample:"
            ls -la out/lib64 | head -n 80 || true
          fi
          if [ -f out/playwright-install.log ]; then
            echo "playwright-install.log tail:"
            tail -n 400 out/playwright-install.log || true
          fi

      - name: Zip layer
        run: |
          cd out
          zip -r ../playwright_layer_py312.zip .
          cd ..
          ls -lh playwright_layer_py312.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-layer-py312
          path: playwright_layer_py312.zip