name: Build Playwright Chromium Layer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build complete layer
        run: |
          set -eo pipefail
          mkdir -p out
          
          # Crear estructura de directorios
          mkdir -p out/python
          mkdir -p out/bin
          
          echo "Instalando Playwright y Chromium en contenedor Amazon Linux..."
          docker run --rm \
            -v "$(pwd)/out:/out" \
            public.ecr.aws/amazonlinux/amazonlinux:2023 \
            bash -c "
            # Instalar dependencias del sistema
            dnf update -y
            dnf install -y \
              python3.11 python3.11-pip \
              tar xz unzip curl \
              fontconfig freetype freetype-devel \
              libX11 libXcomposite libXcursor libXdamage \
              libXrandr libXtst libXrender libxcb \
              libxshmfence libxkbcommon atk gtk3 \
              pango alsa-lib cups-libs dbus-glib \
              libnss3 nspr at-spi2-atk libdrm \
              mesa-libgbm
            
            # Instalar Playwright
            pip3.11 install playwright==1.55.0 --target /out/python
            
            # Instalar Chromium con Playwright
            export PLAYWRIGHT_BROWSERS_PATH=/out/ms-playwright
            python3.11 -m playwright install chromium --with-deps
            
            # Crear script wrapper para chromium
            cat > /out/bin/chromium << 'EOF'
            #!/bin/bash
            export PLAYWRIGHT_BROWSERS_PATH=/opt/ms-playwright
            exec /opt/ms-playwright/chromium-*/chrome-linux/chrome \"\$@\"
            EOF
            chmod +x /out/bin/chromium
            
            # Verificar instalación
            echo '=== Chromium instalado en ==='
            find /out/ms-playwright -name 'chrome' -type f
            "

      - name: Verify installation
        run: |
          echo "=== Estructura de out ==="
          find out -type f -name "chrome" | head -5
          echo "=== Playwright Python ==="
          ls -la out/python/playwright* | head -10

      - name: Create layer zip
        run: |
          cd out
          zip -r ../playwright_chromium_layer.zip .
          cd ..
          echo "Layer size:"
          ls -lh playwright_chromium_layer.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-chromium-layer
          path: playwright_chromium_layer.zip